"""Event catalog, generated from the schema package (S01.3.3).

    uv run python -m riven_schemas.catalog > docs/events.md

A test fails when docs/events.md is out of date or an event has no catalog entry.
"""

import json
from dataclasses import dataclass

from riven_schemas import SCHEMA_VERSION
from riven_schemas.contracts import EVENTS


@dataclass(frozen=True)
class Route:
    producer: str
    consumers: tuple[str, ...]


# Producer and consumer services per docs/adr/0002-service-decomposition.md.
ROUTES: dict[str, Route] = {
    "change.captured": Route("capture", ("orchestrator", "graph")),
    "verification.completed": Route("orchestrator", ("memory", "graph")),
    "bug.confirmed": Route("memory", ("graph",)),
    "regression.detected": Route("memory", ("graph",)),
    "lock.created": Route("memory", ("graph",)),
}


def render() -> str:
    lines = [
        "# Event catalog",
        "",
        "<!-- Generated by `uv run python -m riven_schemas.catalog > docs/events.md`. "
        "Do not edit. -->",
        "",
        f"Schema version **{SCHEMA_VERSION}**. Events are written to the transactional outbox "
        "in the same database transaction as the state change, relayed to the Redis Stream "
        "`riven:events`, and delivered at least once. Consumers deduplicate on `event_id`.",
        "",
        "| Event | Producer | Consumers | Meaning |",
        "|---|---|---|---|",
    ]
    for event in EVENTS:
        name = event.model_fields["type"].default
        route = ROUTES[name]
        lines.append(
            f"| [`{name}`](#{name.replace('.', '')}) | {route.producer} | "
            f"{', '.join(route.consumers)} | {(event.__doc__ or '').strip()} |"
        )
    for event in EVENTS:
        name = event.model_fields["type"].default
        schema = json.dumps(event.model_json_schema(), indent=2, sort_keys=True)
        lines += ["", f"## {name}", "", f"Model: `riven_schemas.{event.__name__}`", ""]
        lines += ["```json", schema, "```"]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    print(render(), end="")
