"""Permission matrix (S03.3.1) — the single source for API enforcement, the UI and the docs.

Regenerate the documented matrix with `uv run python -m riven_api.auth.permissions >
docs/permissions.md`; a test fails when it is stale.
"""

from enum import StrEnum

from riven_schemas import Role


class Permission(StrEnum):
    ORG_READ = "org.read"
    ORG_UPDATE = "org.update"
    ORG_DELETE = "org.delete"
    ORG_SECURITY = "org.security"
    MEMBERS_READ = "members.read"
    MEMBERS_INVITE = "members.invite"
    MEMBERS_UPDATE_ROLE = "members.update_role"
    MEMBERS_REMOVE = "members.remove"
    API_KEYS_READ = "api_keys.read"
    API_KEYS_MANAGE = "api_keys.manage"
    REPOS_READ = "repos.read"
    REPOS_MANAGE = "repos.manage"
    CHANGES_READ = "changes.read"
    CHANGES_SUBMIT = "changes.submit"
    RUNS_READ = "runs.read"
    RUNS_CANCEL = "runs.cancel"
    BUGS_READ = "bugs.read"
    BUGS_CONFIRM = "bugs.confirm"
    REVIEWS_APPROVE = "reviews.approve"
    LOCKS_CREATE = "locks.create"
    LOCKS_RETIRE = "locks.retire"
    GRAPH_READ = "graph.read"
    AUDIT_READ = "audit.read"


DESCRIPTIONS: dict[Permission, str] = {
    Permission.ORG_READ: "See the organization",
    Permission.ORG_UPDATE: "Rename the organization",
    Permission.ORG_DELETE: "Delete the organization",
    Permission.ORG_SECURITY: "Change security policy (require MFA)",
    Permission.MEMBERS_READ: "See members",
    Permission.MEMBERS_INVITE: "Invite members",
    Permission.MEMBERS_UPDATE_ROLE: "Change a member's role",
    Permission.MEMBERS_REMOVE: "Remove a member",
    Permission.API_KEYS_READ: "See service accounts and API keys (never the secrets)",
    Permission.API_KEYS_MANAGE: "Create, rotate and revoke API keys",
    Permission.REPOS_READ: "See repositories",
    Permission.REPOS_MANAGE: "Connect and configure repositories",
    Permission.CHANGES_READ: "See changes and who produced them",
    Permission.CHANGES_SUBMIT: "Submit a change for verification",
    Permission.RUNS_READ: "See verification runs and logs",
    Permission.RUNS_CANCEL: "Cancel a verification run",
    Permission.BUGS_READ: "See bug memory",
    Permission.BUGS_CONFIRM: "Confirm or dismiss a detected bug",
    Permission.REVIEWS_APPROVE: "Approve or reject a 'Needs Review' run",
    Permission.LOCKS_CREATE: "Create a regression lock",
    Permission.LOCKS_RETIRE: "Retire a regression lock",
    Permission.GRAPH_READ: "Explore the causal graph",
    Permission.AUDIT_READ: "Read the audit log",
}

_READ = {
    Permission.ORG_READ,
    Permission.MEMBERS_READ,
    Permission.REPOS_READ,
    Permission.CHANGES_READ,
    Permission.RUNS_READ,
    Permission.BUGS_READ,
    Permission.GRAPH_READ,
}
_REVIEW = _READ | {Permission.BUGS_CONFIRM, Permission.REVIEWS_APPROVE}
_MAINTAIN = _REVIEW | {
    Permission.API_KEYS_READ,
    Permission.REPOS_MANAGE,
    Permission.CHANGES_SUBMIT,
    Permission.RUNS_CANCEL,
    Permission.LOCKS_CREATE,
}
_ADMIN = _MAINTAIN | {
    Permission.ORG_UPDATE,
    Permission.ORG_SECURITY,
    Permission.MEMBERS_INVITE,
    Permission.MEMBERS_UPDATE_ROLE,
    Permission.MEMBERS_REMOVE,
    Permission.API_KEYS_MANAGE,
    Permission.LOCKS_RETIRE,
    Permission.AUDIT_READ,
}

MATRIX: dict[Role, frozenset[Permission]] = {
    Role.OWNER: frozenset(Permission),
    Role.ADMIN: frozenset(_ADMIN),
    Role.MAINTAINER: frozenset(_MAINTAIN),
    Role.REVIEWER: frozenset(_REVIEW),
    Role.VIEWER: frozenset(_READ),
}

RULES = [
    "Only owners can make someone an owner, change an owner's role or remove an owner.",
    "An organization always keeps at least one owner.",
    "A service account's API key carries explicit scopes; each scope must be a permission "
    "its creator holds (S03.4).",
    "Independence: whoever produced a change can never approve its review (S07.6).",
]


def allowed(role: Role, permission: Permission) -> bool:
    return permission in MATRIX[role]


def render() -> str:
    roles = list(Role)
    lines = [
        "# Permission matrix",
        "",
        "<!-- Generated by `uv run python -m riven_api.auth.permissions > docs/permissions.md`."
        " Do not edit. -->",
        "",
        "Enforced by the API (`require(Permission.…)` on every endpoint, deny by default) and "
        "mirrored in the dashboard, which hides actions the caller cannot perform.",
        "",
        "| Permission | Meaning | " + " | ".join(r.value.title() for r in roles) + " |",
        "|---|---|" + "---|" * len(roles),
    ]
    for p in Permission:
        marks = " | ".join("✓" if allowed(r, p) else "—" for r in roles)
        lines.append(f"| `{p.value}` | {DESCRIPTIONS[p]} | {marks} |")
    lines += ["", "## Rules", ""] + [f"- {rule}" for rule in RULES]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    print(render(), end="")
