"""S01.4: baseline domain tables, every one scoped by an indexed org_id.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-27 03:27:11.134523
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_nodes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("key", sa.String(length=1000), nullable=False),
        sa.Column("label", sa.String(length=500), nullable=False),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "kind", "key"),
    )
    op.create_index(op.f("ix_graph_nodes_org_id"), "graph_nodes", ["org_id"], unique=False)
    op.create_table(
        "repositories",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "full_name"),
    )
    op.create_index(op.f("ix_repositories_org_id"), "repositories", ["org_id"], unique=False)
    op.create_table(
        "changes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=True),
        sa.Column("producer_kind", sa.String(length=16), nullable=False),
        sa.Column("producer_identity", sa.String(length=255), nullable=False),
        sa.Column("agent_model", sa.String(length=128), nullable=True),
        sa.Column("files_changed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "repository_id", "commit_sha"),
    )
    op.create_index(op.f("ix_changes_org_id"), "changes", ["org_id"], unique=False)
    op.create_table(
        "graph_edges",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("provenance", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["graph_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["graph_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graph_edges_org_id"), "graph_edges", ["org_id"], unique=False)
    op.create_index(
        "ix_graph_edges_org_source", "graph_edges", ["org_id", "source_id"], unique=False
    )
    op.create_index(
        "ix_graph_edges_org_target", "graph_edges", ["org_id", "target_id"], unique=False
    )
    op.create_table(
        "bugs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("module", sa.String(length=500), nullable=True),
        sa.Column("first_seen_change_id", sa.Uuid(), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_change_id"],
            ["changes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "repository_id", "fingerprint"),
    )
    op.create_index(op.f("ix_bugs_org_id"), "bugs", ["org_id"], unique=False)
    op.create_table(
        "verification_runs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("change_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=True),
        sa.Column("verifier_identity", sa.String(length=255), nullable=False),
        sa.Column("stages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_id"],
            ["changes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_index(
        op.f("ix_verification_runs_change_id"), "verification_runs", ["change_id"], unique=False
    )
    op.create_index(
        op.f("ix_verification_runs_org_id"), "verification_runs", ["org_id"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["verification_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(op.f("ix_artifacts_org_id"), "artifacts", ["org_id"], unique=False)
    op.create_index(op.f("ix_artifacts_run_id"), "artifacts", ["run_id"], unique=False)
    op.create_table(
        "regression_locks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("bug_id", sa.Uuid(), nullable=False),
        sa.Column("test_ref", sa.String(length=1000), nullable=False),
        sa.Column("fixed_by_change_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bug_id"],
            ["bugs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fixed_by_change_id"],
            ["changes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_regression_locks_bug_id"), "regression_locks", ["bug_id"], unique=False
    )
    op.create_index(
        op.f("ix_regression_locks_org_id"), "regression_locks", ["org_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_regression_locks_org_id"), table_name="regression_locks")
    op.drop_index(op.f("ix_regression_locks_bug_id"), table_name="regression_locks")
    op.drop_table("regression_locks")
    op.drop_index(op.f("ix_artifacts_run_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_org_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_verification_runs_org_id"), table_name="verification_runs")
    op.drop_index(op.f("ix_verification_runs_change_id"), table_name="verification_runs")
    op.drop_table("verification_runs")
    op.drop_index(op.f("ix_bugs_org_id"), table_name="bugs")
    op.drop_table("bugs")
    op.drop_index("ix_graph_edges_org_target", table_name="graph_edges")
    op.drop_index("ix_graph_edges_org_source", table_name="graph_edges")
    op.drop_index(op.f("ix_graph_edges_org_id"), table_name="graph_edges")
    op.drop_table("graph_edges")
    op.drop_index(op.f("ix_changes_org_id"), table_name="changes")
    op.drop_table("changes")
    op.drop_index(op.f("ix_repositories_org_id"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_graph_nodes_org_id"), table_name="graph_nodes")
    op.drop_table("graph_nodes")
    # ### end Alembic commands ###
