"""S03.2: organizations and row-level security

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-27 05:11:59.321616
"""

import sqlalchemy as sa
from alembic import op

from riven_db.rls import create_app_role_sql, disable_rls, enable_rls

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None

# Frozen list: later tenant tables enable RLS in their own migration.
TENANT_TABLES = (
    "repositories",
    "changes",
    "verification_runs",
    "artifacts",
    "bugs",
    "regression_locks",
    "graph_nodes",
    "graph_edges",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("require_mfa", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        info={"tenant_scoped": False},
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["accepted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
        info={"tenant_scoped": False},
    )
    op.create_index(op.f("ix_invitations_org_id"), "invitations", ["org_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("org_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("org_id", "user_id"),
        info={"tenant_scoped": False},
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # Row-level security on every tenant table (tables with org_id, except identity tables).
    for statement in create_app_role_sql():
        op.execute(statement)
    for table in TENANT_TABLES:
        enable_rls(op, table)


def downgrade() -> None:
    for table in TENANT_TABLES:
        disable_rls(op, table)
    # The role is cluster-wide (other databases may use it); only drop what this one granted.
    op.execute("REVOKE ALL ON ALL TABLES IN SCHEMA public FROM riven_app")
    op.execute("REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM riven_app")
    op.execute("REVOKE USAGE ON SCHEMA public FROM riven_app")
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM riven_app"
    )
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM riven_app"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_invitations_org_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
