"""S03.5: revoked sessions

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-27 05:46:45.254797
"""

import sqlalchemy as sa
from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revoked_sessions",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
        info={"tenant_scoped": False},
    )
    op.create_index(
        op.f("ix_revoked_sessions_expires_at"), "revoked_sessions", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_revoked_sessions_expires_at"), table_name="revoked_sessions")
    op.drop_table("revoked_sessions")
    # ### end Alembic commands ###
